In [1]:
import pandas as pd

data = pd.read_csv("used_phone_price.csv")

data.head()

,brand,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,os_type,...,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,market_demand_score,resale_price
0,Realme,Realme GT,2025,4,256,6.93,4130,47,100,Android,...,0,0,0,Tier1,Individual,11,1,1,99,47891.46
1,Samsung,Galaxy S21,2024,16,64,6.29,5558,81,67,Android,...,0,0,0,Tier3,Store,8,1,0,64,17663.21
2,Apple,iPhone 11,2022,4,128,5.52,5945,59,67,iOS,...,0,0,0,Tier1,Individual,0,0,1,68,67268.20
3,Google,Pixel 6,2024,16,512,5.99,5767,84,57,Android,...,0,0,1,Tier1,Store,11,1,1,50,12626.26
4,Google,Pixel 7,2021,4,128,6.59,5336,98,44,Android,...,0,0,0,Tier3,Store,24,1,1,66,20662.25

In [9]:
print(data["screen_size_inches"].min())
print(data["screen_size_inches"].max())

5.5
7.0

In [10]:
data["ram_gb"].value_counts()

ram_gb
12    2065
6     2025
16    2008
4     1955
8     1947
Name: count, dtype: int64

In [11]:
data["storage_gb"].value_counts()

storage_gb
1024    2030
512     2026
128     2004
64      1981
256     1959
Name: count, dtype: int64

In [12]:
data["processor_score"].value_counts()

processor_score
58    195
51    191
55    190
50    186
92    185
     ...
48    147
44    146
62    141
64    140
45    137
Name: count, Length: 61, dtype: int64

In [14]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "used_phone_price_prediction_1M.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "sharmajicoder/used-phone-price-prediction-dataset",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

C:\Users\cheta\AppData\Local\Temp\ipykernel_9932\830399820.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to C:\Users\cheta\.cache\kagglehub\datasets\sharmajicoder\used-phone-price-prediction-dataset\versions\1\used_phone_price_prediction_1M.csv...

100%|██████████| 116M/116M [00:11<00:00, 10.3MB/s]

First 5 records:      brand       model  release_year  ram_gb  storage_gb  screen_size_inches  \
0   Realme   Realme GT          2025       4         256                6.93
1  Samsung  Galaxy S21          2024      16          64                6.29
2    Apple   iPhone 11          2022       4         128                5.52
3   Google     Pixel 6          2024      16         512                5.99
4   Google     Pixel 7          2021       4         128                6.59

   battery_capacity  processor_score  camera_score  os_type  ...  body_damage  \
0              4130               47           100  Android  ...            0
1              5558               81            67  Android  ...            0
2              5945               59            67      iOS  ...            0
3              5767               84            57  Android  ...            0
4              5336               98            44  Android  ...            0

   repair_history  water_damage  city_tier  seller_type  \
0               0             0      Tier1   Individual
1               0             0      Tier3        Store
2               0             0      Tier1   Individual
3               0             1      Tier1        Store
4               0             0      Tier3        Store

  warranty_remaining_months  box_available  charger_available  \
0                        11              1                  1
1                         8              1                  0
2                         0              0                  1
3                        11              1                  1
4                        24              1                  1

   market_demand_score  resale_price
0                   99      47891.46
1                   64      17663.21
2                   68      67268.20
3                   50      12626.26
4                   66      20662.25

[5 rows x 28 columns]

In [15]:
df

,brand,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,os_type,...,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,market_demand_score,resale_price
0,Realme,Realme GT,2025,4,256,6.93,4130,47,100,Android,...,0,0,0,Tier1,Individual,11,1,1,99,47891.46
1,Samsung,Galaxy S21,2024,16,64,6.29,5558,81,67,Android,...,0,0,0,Tier3,Store,8,1,0,64,17663.21
2,Apple,iPhone 11,2022,4,128,5.52,5945,59,67,iOS,...,0,0,0,Tier1,Individual,0,0,1,68,67268.20
3,Google,Pixel 6,2024,16,512,5.99,5767,84,57,Android,...,0,0,1,Tier1,Store,11,1,1,50,12626.26
4,Google,Pixel 7,2021,4,128,6.59,5336,98,44,Android,...,0,0,0,Tier3,Store,24,1,1,66,20662.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,Samsung,Galaxy A54,2023,6,128,6.61,6358,99,63,Android,...,0,0,0,Tier3,Store,11,1,1,95,56194.05
999996,Samsung,Galaxy A54,2021,16,512,6.19,6142,63,43,Android,...,0,0,0,Tier3,Store,11,0,1,65,2040.32
999997,Apple,iPhone 15,2022,4,256,5.97,5874,79,49,iOS,...,0,0,0,Tier2,Individual,14,0,1,99,31236.16
999998,Apple,iPhone 13,2023,12,512,6.73,5220,53,56,iOS,...,0,0,0,Tier3,Store,17,1,1,57,16288.20
999999,Realme,Realme GT,2020,16,256,6.16,6463,91,51,Android,...,0,1,0,Tier2,Individual,10,1,1,83,9819.03